### ISSUE TITLE
Errors compiling MetalImageDisplay example

### ISSUE THREAD

**Issue by JohnCoates** [erickingxu/MetalImage#1]
I get these errors when compiling: 

Showing Recent Issues
/Users/macbook/Dev/Clones/MetalImage/examples/MetalImageDisplay/MetalImageDisplay/ViewController.m:68:17: Property 'filterDelegate' not found on object of type 'MetalImageView *'

/Users/macbook/Dev/Clones/MetalImage/examples/MetalImageDisplay/MetalImageDisplay/ViewController.m:81:14: No visible @interface for 'MetalImageFilter' declares the selector 'configure:'

/Users/macbook/Dev/Clones/MetalImage/examples/MetalImageDisplay/MetalImageDisplay/ViewController.m:82:34: No visible @interface for 'MetalImageView' declares the selector 'display'

**Comment by erickingxu** [comment]
Hi @JohnCoates ,
BUGS Had been fixed.

**Comment by JohnCoates** [comment]
Awesome, thanks! Nice job with your framework btw. I'm just starting a camera project and definitely interested in using Metal
