### ISSUE TITLE
Filter chain

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [erickingxu/MetalImage#10]
Sorry. This isn't an issue. Just a question. How can we apply a filter chain? Let's say we want to do a beauty filter and an imagetonecurve filter at the same time.

**Comment by erickingxu** [comment]
it is very simple, you can new a beautyfliter and curve filter and a Metalimageview for show result.
And then, addTarget one by one, it will auto-work without any other operations.
See the example , MetalVideoFilter folder
Thx from ek
