### ISSUE TITLE
MetalFaceFilter Demo不能运行

### ISSUE THREAD

**Issue by youngliuxx** [erickingxu/MetalImage#13]
提示：
```
validateFunctionArguments:2793: failed assertion `missing buffer binding at index 0 for pPosition[0].'
```
这是调用栈：

![image](https://user-images.githubusercontent.com/29717913/37033978-c1c6bcaa-2182-11e8-8bba-0d582e210957.png)

**Comment by erickingxu** [comment]
Hi @youngliuxx 
This 2793 is  an metal bug ,you can google it, and change xcode metal debug configures , that will be ok.
