### ISSUE TITLE
different filter's texture size

### ISSUE THREAD

**Issue by swlfigo** [erickingxu/MetalImage#4]
hi, i'd to ask , if i have two filter, filterA and filterB, how to set filter A output frame( output texture size) , and how to set filter B content size (accept filter A texture size),

**Comment by erickingxu** [comment]
Hi @swlfigo ,
every filter had a input texture and an output texture(MetalImageTexture class), you just need to set the filter chain's firstInputTexture of first filter, and other filters in this chain will use last filter's output texture size as default.
details ,refer to MetalImageTexture class, like as follows:
[[MetalImageTexture alloc] initWithWidth:(uint32_t)width withHeight:(uint32_t)height];

And I will give more fitness interface for filter size in next version later, thx from ek

**Comment by swlfigo** [comment]
hi,thx for answering my question, i dont know  English quite well, maybe i cant describe my question precisely , i know what ur meaning . But , i want to ask is , the first filter output texture size is (1000 , 1000) , and second filter content size is (300,300) , how to set up filter with ur framework, i try to create a texture size (300 , 300), ( modify from Apple Sample : ImageProcessing ) , but the texture is croped to (300 ,300), part of first filter texture(300 ,300 ), i am beginner of Metal , 

btw, are u Chinese ? i find there are some Chinese in ur repositories !

**Comment by erickingxu** [comment]
hi @swlfigo 
I add cropFilter for your request to output a different filter texture size.
you can try it.
Thanks from EK
