### ISSUE TITLE
Hope a performance compare between MetalImage and GPUImage

### ISSUE THREAD

**Issue by stayHF** [erickingxu/MetalImage#5]
Thanks for the great idea. 
It'a amazing if a performance compare result in the Readme.md.

**Comment by erickingxu** [comment]
@stayHF ,
Yes, I try to give details for comparison between two lib.
But I had tried to compare some gaussian algorithm for beauty face , Metal can give a 30 FPS ,and Opengles just give 23 FPS on iPhone 6s.
Thanks from EK
