### ISSUE TITLE
Process many times crash

### ISSUE THREAD

**Issue by swlfigo** [erickingxu/MetalImage#6]
hello again. i recently write a metal to process image , i find that your project has a same problem. if i process many times, it will crash, Example, i add a UIPanGestureRecognizer ,  move very fast (simulate two image combine to a new one by moving finger), it will crash, but my project will stop for a second, i log in console , find that CAMetalLayer will nil sometime

**Comment by erickingxu** [comment]
Can you tell me which filter produced this problem? details refer for my fix work.
And seemed some old bugs which metalayer  size is zero caused. I will check it later...

**Comment by erickingxu** [comment]
@swlfigo ,
I had fixed the crash caused by MetalImagePicture  processing  many times.
Maybe you can test it.
Thanks from ek
