### ISSUE TITLE
I would like to see an example of using "SumReduce.metal"

### ISSUE THREAD

**Issue by leeys888** [erickingxu/MetalImage#7]
I would like to see an example of using "SumReduce.metal"
What is sumReduceOptimize_X , sumReduceOptimize_Y ??

**Comment by erickingxu** [comment]
Hi @leeys888 ,
This metal kernel is for calculating a mean of image with NVIDIA algorithm named  "reduce" with gpu in 1-D array.
So I try to implement it with metal kernel for a better speed. Maybe need some time to test it in example. So please wait and keep watch this project.
Thanks from ek
