### ISSUE TITLE
more faster is incorrect 

### ISSUE THREAD

**Issue by aelam** [erickingxu/MetalImage#8]
Should be much faster

**Comment by erickingxu** [comment]
Hi @aelam 
Thanks first, faster means in some filter like gaussian or beauty filter , and 3d drawing.
Maybe some filters which are not optimised could be slow or the same as opengles ,and I will give some optimization later.

**Comment by aelam** [comment]
I mean the grammar 'more faster' is incorrect 
It should be 'much faster', not about the performance 


发自我的 iPhone
