### ISSUE TITLE
Adding custom acv file causes crash

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [erickingxu/MetalImage#9]
MetalImageToneCurveFilter crashes with using custom acv file. I get this.

MetalVideoFilter[9484:4178299] failed to init ACVFile with data:(null)
validateComputeFunctionArguments:720: failed assertion `missing buffer binding at index 0 for curveBuffer[0].'

Then line 191 of MetalImageToneCurveFilter.mm is highlighted. This line [cmputEncoder  dispatchThreadgroups:_threadGroupCount threadsPerThreadgroup:_threadGroupSize];

**Comment by erickingxu** [comment]
Hi Marc
I think it is a resource loading failed error, maybe you should add acv file into item "Copy Bundle Resources" in Build Phases .
thanks
